<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) ){
	$params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
        <?php endif; ?>

        <p class="form-paragr">
	        <?php echo $this->aux_form->comboSelect('tipo', 'tipo', $mod->tipo, TXT_ROTULO_TIPO, null, ['required' => 'required'],
		        array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], $params['tipos'])
	        ); ?>

            <?php
	        if( $params['novo-tipo?'] ){
		        echo $this->aux_links->linkHTML('inserir', 'javascript:', sprintf(TXT_LINK_NOVO, TXT_MODELO_TIPODADOCONTATO), null, true,
			        ['data-acao' => 'carregar-form', 'data-acao-param-html' => 'website/tipos-de-dados/novo', 'data-acao-param-func' => "carregarSelect($('#sel-tipo'), 'website/tipos-de-dados/carregar-select')", 'data-ajax' => true, 'data-ajax-msg' => TXT_AJAX_CARREGANDO_CONTEUDO]);
	        } // Fim if
	        ?>
        </p>

        <p class="form-paragr">
            <?php echo $this->aux_form->campoGeral('texto', 'descr', 'descr', $mod->descr, TXT_ROTULO_DESCR, null, [
	            'pattern' => !empty($params['expreg']) ? $params['expreg'] : null,
                'placeholder' => $params['exemplo'],
                'required' => 'required'
            ]); ?>
        </p>

        <p class="form-paragr">
	        <?php echo $this->aux_form->chkSimNao('publicar', 'publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
        </p>

        <p class="form-botoes">
            <?php
            echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
            echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
            ?>
        </p>
    </form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    (function($){
        var $descr = $('#txt-descr');

        <?php if (!empty($params['mascara'])): ?>
            // Aplicar a máscara
            $descr.mascara('<?php echo $params['mascara']; ?>');
        <?php endif; ?>

        $('#sel-tipo').on('change', function(){
            var tipo = $(this).val();

            $.ajax({
                url     : 'website/tipos-de-dados/opcoes-avancadas',
                type    : 'post',
                dataType: 'json',
                data    : 'id='+ tipo,
                success : function(j){
                    if (j.mascara === '') {
                        $descr.removerMascara();
                    } else {
                        $descr.mascara(j.mascara);
                    } // Fim if ... else

                    if (j.expreg === '') {
                        $descr.removeAttr('pattern');
                    } else {
                        $descr.attr({ pattern: j.expreg });
                    } // Fim if ... else

                    if (j.exemplo === '') {
                        $descr.removeAttr('placeholder');
                    } else {
                        $descr.attr({ placeholder: j.exemplo });
                    } // Fim if ... else
                }
            });
        });
    })(jQuery);
    //]]>
</script>
[/DL3-SCRIPTS]
