<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 07/01/2015 18:34:49
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
<form id="form-<?php echo $params['form-id']; ?>" method="post"
      action="<?php echo $params['form-action']; ?>"<?php echo $params['incluindo'] ? ' enctype="multipart/form-data"' : ''; ?>>
    <?php if (!$params['incluindo']): ?>
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
    <?php endif; ?>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo TXT_LEGENDA_ALBUM_FOTOS; ?></legend>

        <p class="form-paragr">
            <?php echo $this->aux_form->campoGeral('texto', 'nome', 'nome', $mod->nome, TXT_ROTULO_NOME, null, ['required' => 'required']); ?>
        </p>

        <?php if ($params['incluindo']): ?>
            <p class="form-paragr">
                <?php echo $this->aux_form->arquivoUpload('fotos[]', 'arq-fotos', TXT_ROTULO_FOTOS, ['multiple' => 'multiple'], $params['extensoes']); ?>
            </p>
        <?php endif; ?>

        <p class="form-paragr">
            <?php echo $this->aux_form->chkSimNao('publicar', 'chk-publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? 'CHECKED' : ''); ?>
        </p>
    </fieldset>

    <p class="form-botoes">
        <?php
        echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
        echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
        ?>
    </p>
</form>
[/DL3-CONTEUDO]