<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 07/01/2015 18:34:49
 */

/*
 * TAREFA: incluir ou criar editores HTML para os textareas
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
<form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
    <?php if (!$params['incluindo']): ?>
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
    <?php endif; ?>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo TXT_LEGENDA_HISTORIA; ?></legend>

        <p class="form-paragr">
            <?php echo $this->aux_form->caixaTexto('historia', 'historia', $mod->historia); ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo TXT_LEGENDA_MISSAO; ?></legend>

        <p class="form-paragr">
            <?php echo $this->aux_form->caixaTexto('missao', 'missao', $mod->missao); ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo TXT_LEGENDA_VISAO; ?></legend>

        <p class="form-paragr">
            <?php echo $this->aux_form->caixaTexto('visao', 'visao', $mod->visao); ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo TXT_LEGENDA_VALORES; ?></legend>

        <p class="form-paragr">
            <?php echo $this->aux_form->caixaTexto('valores', 'valores', $mod->valores); ?>
        </p>
    </fieldset>

    <p class="form-botoes">
        <?php
        echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
        echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
        ?>
    </p>
</form>
[/DL3-CONTEUDO]