<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) ){
	$params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
        <input type="hidden" name="foto_album" value="<?php echo $mod->foto_album; ?>"/>

        <figure class="mostrar-imagem">
            <img src="<?php echo \DL3::$dir_relativo . $mod->imagem; ?>" alt=""/>
        </figure>

        <p class="form-paragr">
	        <?php echo $this->aux_form->campoGeral('texto', 'titulo', 'titulo', $mod->titulo, TXT_ROTULO_TITULO); ?>
        </p>

        <p class="form-paragr">
            <label for="txt-descr" class="form-rotulo"><?php echo TXT_ROTULO_DESCR; ?>:</label><br/>
            <textarea name="descr" id="txt-descr" class="form-controle form-controle-textarea"><?php echo $mod->descr; ?></textarea>
        </p>

        <p class="form-paragr">
            <?php echo $this->aux_form->chkSimNao('capa', 'capa', TXT_ROTULO_CAPA, MSG_DICA_ALBUMFOTO_CAPA, $mod->capa ? ' CHECKED' : ''); ?>
        </p>

        <p class="form-paragr">
            <?php echo $this->aux_form->chkSimNao('publicar', 'publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
        </p>

        <p class="form-botoes">
            <?php
            echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
            echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
            ?>
        </p>
    </form>
[/DL3-CONTEUDO]