<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if (!isset($params)) {
	$params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>

        <p class="msg-info"><?php echo TXT_DIVERSOS_CONFIGURACAO_WEBSITE; ?></p>

        <p class="form-paragr">
            <?php echo $this->aux_form->comboSelect('tema', 'tema', $mod->tema, TXT_ROTULO_TEMA, null, ['required' => 'required'],
                array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], (array)$params['temas'])
            ); ?>
        </p>

        <p class="form-paragr">
	        <?php echo $this->aux_form->comboSelect('formato_data', 'formato_data', $mod->formato_data, TXT_ROTULO_FORMATO_DATA, TXT_DICA_WEBSITE_FORMATO_DATA, ['required' => 'required'],
		        array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], (array)$params['formatos-data'])
	        ); ?>
        </p>

        <?php if (count($params['confs-email']) > 0): ?>
            <p class="form-paragr">
                <?php echo $this->aux_form->comboSelect('email', 'email', $mod->email, TXT_ROTULO_CONFIGURACAO_EMAIL, TXT_DICA_WEBSITE_CONFIGURACAO_EMAIL, ['required' => 'required'],
                    array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], (array)$params['confs-email'])
                ); ?>
            </p>
        <?php endif; ?>

        <p class="form-botoes">
            <?php
            echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
            echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
			?>
        </p>
    </form>
[/DL3-CONTEUDO]