<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 07/01/2015 18:34:49
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
<form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>"
      enctype="multipart/form-data">
    <?php if (!$params['incluindo']): ?>
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
    <?php endif; ?>

    <p class="form-paragr">
        <?php echo $this->aux_form->campoGeral('texto', 'apelido', 'apelido', $mod->apelido, TXT_ROTULO_APELIDO, null); ?>
    </p>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo TXT_LEGENDA_CONTA_GOOGLE; ?></legend>

        <p class="form-paragr">
            <?php echo $this->aux_form->campoGeral('texto', 'usuario', 'usuario', $mod->usuario, TXT_ROTULO_USUARIO, null, [
                'style'    => 'width: 20%;',
                'required' => 'required'
            ]); ?>
            @developer.gserviceaccount.com
        </p>

        <p class="form-paragr">
            <?php echo $this->aux_form->arquivoUpload('p12', 'p12', TXT_ROTULO_P12, [
                'required' => $mod->p12 === '' ? 'required' : null
            ], 'p12'); ?>
            <br/><span class="form-dica"><?php echo TXT_DICA_P12; ?></span>

            <?php if (strlen($mod->p12) > 0) {
                echo '<br/>', $this->aux_links->linkHTML('detalhes', \DL3::$dir_relativo . $mod->p12, TXT_LINK_DOWNLOAD_ARQUIVO_ATUAL, null, true, [
                    'target' => '_blank'
                ]);
            } // Fim if ?>
        </p>
    </fieldset>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo TXT_LEGENDA_CONFIGURACOES; ?></legend>

        <p class="form-paragr">
            <?php echo $this->aux_form->campoGeral('numero', 'perfil_id', 'perfil-id', $mod->perfil_id, TXT_ROTULO_PERFIL, null, [
                'min' => 10000, 'max' => 999999999, 'required' => 'required'
            ]); ?>
        </p>

        <p class="form-paragr">
            <?php echo $this->aux_form->campoGeral('texto', 'codigo_ua', 'codigo-ua', $mod->codigo_ua, TXT_ROTULO_CODIGO_UA, null, ['required' => 'required']); ?>
        </p>
    </fieldset>

    <p class="form-paragr">
        <?php echo $this->aux_form->chkSimNao('principal', 'principal', TXT_ROTULO_PRINCIPAL, null, $mod->principal ? ' CHECKED' : ''); ?>
    </p>

    <p class="form-paragr">
        <?php echo $this->aux_form->chkSimNao('publicar', 'publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
    </p>

    <p class="form-botoes">
        <?php
        echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
        echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
        ?>
    </p>
</form>
[/DL3-CONTEUDO]
