<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 07/01/2015 18:34:49
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
<form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
    <?php if (!$params['incluindo']): ?>
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
    <?php endif; ?>

    <p class="form-paragr">
        <?php echo $this->aux_form->campoGeral('texto', 'descr', 'descr', $mod->descr, TXT_ROTULO_DESCR, null, ['required' => 'required']); ?>
    </p>

    <p class="form-paragr">
        <?php echo $this->aux_form->campoGeral('email', 'email', 'email', $mod->email, TXT_ROTULO_EMAIL, null, ['required' => 'required']); ?>
    </p>

    <p class="form-paragr">
        <?php echo $this->aux_form->campoGeral('cor', 'cor', 'cor', $mod->cor, TXT_ROTULO_COR, null, ['required' => 'required']); ?>
    </p>

    <p class="form-paragr">
        <?php echo $this->aux_form->chkSimNao('publicar', 'publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
    </p>

    <p class="form-botoes">
        <?php
        echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
        echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
        ?>
    </p>
</form>
[/DL3-CONTEUDO]
