<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 14/01/2015 10:44:51
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

?>

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $el = $('#form-editar-lista').formulario({
        cktodos: [true, 'thead :checkbox', 'tbody :checkbox'],
        depois: function(){
            var $tbody = $el.find('tbody');

            // Remover o item da lista
            $tbody.find(':checked').parents('tr').remove();

            if ($tbody.find('tr').length === 0) {
                $(document.createElement('tr')).addClass('tbl-linha sem-registros')
                    .html('<td><?php echo MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO; ?></td>')
                    .appendTo($tbody);
            } // Fim if
        },
        aparencia: { tema: '<?php echo DL3::$plugin_formulario_tema; ?>', estilo: null }
    });

    $pg = $('#paginacao').paginacao({
        pgtotal: <?php echo $params['total-pg']; ?>,
        mostrar: 5,
        tema: '<?php echo \DL3::$plugin_paginacao_tema; ?>'
    });

    $('.com-marcados > *:first-child,.sem-registros > *:first-child')
        .attr({ 'colspan': $('.tbl-titulos > .tbl-linha:first-child > *').length });
    //]]>
</script>
[/DL3-SCRIPTS]