<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) ){
	$params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <h2 class="titulo-h2"><?php echo TXT_PAGINA_TITULO_MODULO; ?></h2>

    <form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_MODULO; ?></legend>

            <?php if( $params['modulos-pai'] != false ): ?>
            <p class="form-paragr">
	            <?php echo $this->aux_form->comboSelect('pai', 'pai', $mod->pai, TXT_ROTULO_MODULO_PAI, null, [],
		            array_merge([['VALOR' => '', 'TEXTO' => TXT_OPCAO_SELECIONE_UMA_OPCAO]], $params['modulos-pai'])
	            ); ?>
            </p>
            <?php endif; ?>

            <p class="form-paragr">
                <?php echo $this->aux_form->campoGeral('texto', 'nome', 'nome', $mod->nome, TXT_ROTULO_NOME, null, ['required' => 'required']); ?>
            </p>

            <p class="form-paragr">
                <?php echo $this->aux_form->caixaTexto('descr', 'descr', $mod->descr, TXT_ROTULO_DESCRICAO); ?>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_MENU; ?></legend>

            <p class="form-paragr">
	            <?php echo $this->aux_form->chkSimNao('menu', 'menu', TXT_ROTULO_MENU, TXT_DICA_MODULO_MENU, $mod->menu ? ' CHECKED' : ''); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->campoGeral('texto', 'link', 'link', $mod->link, TXT_ROTULO_LINK, null, ['required' => 'required']); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->campoGeral('numero', 'ordem', 'ordem', $mod->ordem, TXT_ROTULO_ORDEM, null, [
		            'min' => -99, 'max' => 99, 'required' => 'required'
	            ]); ?>
            </p>
        </fieldset>

        <p class="form-paragr">
	        <?php echo $this->aux_form->chkSimNao('publicar', 'publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
        </p>

        <?php if ($params['incluindo']): ?>
            <input type="checkbox" name="criar-funcs" id="chk-criar-funcs" value="1" checked/>
            <label for="chk-criar-funcs"><?php echo TXT_ROTULO_CRIAR_FUNCIONALIDADES_PADRAO; ?></label>
        <?php endif; ?>

        <p class="form-botoes">
            <?php
            echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
            echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
            ?>
        </p>
    </form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $('#sel-pai').on('change', function(){
        var $forms = $('#form-funcs, #form-remover-func');

        $(this).val() !== '' ? $forms.show('fast') : $forms.hide('fast');
    });
    //]]>
</script>
[/DL3-SCRIPTS]
