<?php
/**
 * Created by PhpStorm.
 * User: dlepera
 * Date: 21/08/15
 * Time: 08:34
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$opcoes = $params['opcoes'];
$lista = $params['lista'];
$dir_lista = $params['dir-lista'];

$campos = \Funcoes::removerColuna($lista, [TXT_LISTA_TITULO_ID, 'linha']);

?>

[DL3-CONTEUDO]
<h2 class="titulo-h2"><?php echo TXT_PAGINA_TITULO_FUNCIONALIDADES; ?></h2>

<nav class="dl3-links">
    <?php echo $this->aux_links->linkHTML('inserir', 'javascript:', sprintf(TXT_LINK_NOVA, TXT_MODELO_MODULOFUNC), '', true, [
        'data-ajax'            => true,
        'data-ajax-msg'        => TXT_AJAX_CARREGANDO_CONTEUDO,
        'data-acao'            => 'carregar-form',
        'data-acao-param-html' => "desenvolvedor/modulos/funcionalidades/novo/{$mod->id}"
    ]),

    $this->aux_links->linkHTML('incluir-funcionalidades-padrao', 'javascript:', TXT_LINK_CRIAR_FUNCIONALIDADES_PADRAO, '', true, [
        'data-acao-param-pk' => $mod->id
    ]); ?>
</nav>

<form id="form-remover-func" method="post" action="desenvolvedor/modulos/funcionalidades/excluir">
    <table class="lista-registros">
        <?php if ($params['qtde-registros'] > 0): ?>
            <caption
                class="subtitulo"><?php printf(TXT_LISTA_SUBTITULO_MOSTRANDO_X_REGISTROS, count($lista), $params['qtde-registros']); ?></caption>
        <?php endif; ?>

        <thead class="bloco-titulos">
        <tr class="registro">
            <th id="th-chk" class="dado -chk"><input type="checkbox"/></th>
            <?php
            echo $this->aux_lista->celulaTitulo('th-id', TXT_LISTA_TITULO_ID, ['class' => '-id']);

            foreach ($campos[0] as $tt => $lt) {
                echo $this->aux_lista->celulaTitulo($this->aux_lista->thID($tt), $tt);
            } // Fim foreach

            echo $this->aux_lista->celulaTitulo('th-opcoes', TXT_LISTA_TITULO_OPCOES, ['class' => '-opcoes']);
            ?>
        </tr>
        </thead>

        <tbody class="bloco-registros">
        <?php if (!count($lista)) {
            echo '<tr class="registro sem-registros"><td colspan="3">', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';
        } // Fim if

        foreach ($lista as $k => $l): ?>
            <tr class="registro">
                <td headers="th-chk" class="dado -chk">
                    <input type="checkbox" name="id[]" value="<?php echo $l[TXT_LISTA_TITULO_ID]; ?>"/>
                </td>
                <?php
                echo $this->aux_lista->celulaComum('th-id', $l[TXT_LISTA_TITULO_ID], ['class' => '-id'], TXT_LISTA_TITULO_ID);

                foreach ($campos[$k] as $k2 => $c) {
                    echo $this->aux_lista->celulaComum(
                        $this->aux_lista->thID($k2),
                        $k2 === TXT_LISTA_TITULO_DATA ? \Funcoes::formatarDataHora($c, $_SESSION['formato_data_completo']) : $c,
                        ['class' => preg_match('~<br\/?>~', $c) ? '-infos' : null], $k2
                    );
                } // Fim foreach ?>

                <td headers="th-opcoes" class="dado -opcoes" data-th="<?php echo TXT_LISTA_TITULO_OPCOES; ?>">
                    <?php
                    echo $this->aux_links->linkHTML('editar', 'javascript:', TXT_LINK_EDITAR, TXT_LINK_TITLE_EDITAR, false, [
                        'data-ajax'            => true,
                        'data-ajax-msg'        => TXT_AJAX_CARREGANDO_CONTEUDO,
                        'data-acao'            => 'carregar-form',
                        'data-acao-param-html' => "desenvolvedor/modulos/funcionalidades/editar/{$l[TXT_LISTA_TITULO_ID]}"
                    ]);
                    echo $this->aux_links->linkHTML('remover', 'javascript:', TXT_LINK_REMOVER, TXT_LINK_TITLE_REMOVER, false);
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $el = $('#form-remover-func').formulario({
        depois: function () {
            $('.lista-registros :checked').parents('tr').remove();
        },
        aparencia: {tema: '<?php echo \DL3::$plugin_formulario_tema; ?>', estilo: null}
    });
    //]]>
</script>
[/DL3-SCRIPTS]
