<?php
/**
 * Created by PhpStorm.
 * User: dlepera
 * Date: 05/11/15
 * Time: 17:21
 */

if( !isset($params) ){
    $params = $this->obterParams();
} // Fim if

?>

[DL3-CARREGANDO]
    <!-- Carregando Conteúdo -->
    <div id="dl3-carregando-conteudo" style="
        position: fixed; top: 0; left: 0; z-index: 3;
        width: 100%; height: 100%;
        background: #F4F7FB;
        text-align: center; font-family: sans-serif;
        ">
        <div style="position: absolute; top: 50%; left: 50%; transform: translateY(-75%) translateX(-50%); -webkit-transform: translateY(-75%) translateX(-50%); width: auto;">
            <img src="<?php echo \DL3::$dir_relativo . \DL3::$dir_temas . $params['carregando-tema']; ?>/css/imagens/logotipo.png" style="max-height: 60px; margin-bottom: .5rem; background: #FFF; border-radius: 50%; padding: .35rem; border: 1px solid #EEE;"/>

            <p style="color: #6A8397; font-size: large;">
                Carregando o conteúdo!<br/>
                Por favor, aguarde...
            </p>

            <progress id="barra-de-progresso" max="100">Carregando...</progress>
        </div>
    </div>
[/DL3-CARREGANDO]

[DL3-SCRIPTS]
    <script>
        //<![CDATA[
        $(window).on('load', function(){
            var $cont = $('#dl3-carregando-conteudo');
            var $paragr = $cont.find('> div');

            // Pra direita
            /* $paragr.animate({ left: '-=10%' }, 500, function(){
                $paragr.animate({ left: '150%' }, 650, function(){
                    $cont.fadeOut(100, function(){
                        $(this).remove();
                    });
                });
            });

            // Pra baixo
            $paragr.animate({ top: '-=10%' }, 500, function(){
                $paragr.animate({ top: '150%' }, 650, function(){
                    $cont.fadeOut(100, function(){
                        $(this).remove();
                    });
                });
            }); */

            // Pra cima
            $paragr.animate({ top: '+=10%' }, 500, function(){
                $paragr.animate({ top: '-100%' }, 650, function(){
                    $cont.fadeOut(100, function(){
                        $(this).remove();
                    });
                });
            });
        });
        //]]>
    </script>
[/DL3-SCRIPTS]
