<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 14/01/2015 10:13:48
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

?>

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    $sf = $('#form-<?php echo $params['form-id']; ?>').formulario({
        botoes_msg: {
            '-sucesso': [
                {
                    funcao: function () {
                        var url = '<?php echo $params['url-depois']; ?>';

                        if (!/^\//.test(url)){
                            url = $('base').attr('href') + url;
                        } // Fim if

                        window.location = url;
                    }
                },

                {
                    padrao: true
                }
            ]
        },

        aparencia: {tema: '<?php echo \DL3::$plugin_formulario_tema; ?>', estilo: null}
    }, true).on('reset', function () {
        history.back();
    });
    //]]>
</script>
[/DL3-SCRIPTS]