<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 03/02/2015 11:35:30
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$lista = $params['lista'];

?>

[DL3-CONTEUDO]
<div class="albuns">
    <?php
    if (!count($lista) || $lista === false) {
        echo '<span class="sem-registros">', TXT_DIVERSOS_NENHUM_ALBUM_ENCONTRADO, '</span>';
    } // Fim if

    foreach ($lista as $f): ?>
        <a href="javascript:" data-acao="album-modal"
            data-acao-param-html="albuns-de-fotos/fotos/<?php echo $f['album_id']; ?>"
            data-acao-param-pgmestra="vazio">
            <figure class="album">
                <?php if (!empty($f['foto_album_mini'])): ?>
                    <img src="<?php echo \DL3::$dir_relativo . $f['foto_album_mini']; ?>"
                         alt="<?php echo $f['album_nome']; ?>"
                         class="capa"/>
                <?php endif; ?>

                <figcaption class="infos">
                    <span class="titulo"><?php echo $f['album_nome']; ?></span><br/>
                    <span class="qtdefotos">
                        <?php echo $f['QTDE_FOTOS'] == 1 ? TXT_DIVERSOS_UMA_FOTO : sprintf(TXT_DIVERSOS_X_FOTOS, $f['QTDE_FOTOS']); ?>
                    </span>
                </figcaption>
            </figure>
        </a>
    <?php endforeach; ?>
</div>
[/DL3-CONTEUDO]