<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 03/02/2015 12:36:09
 */

if( !isset($params) ){
	$params = $this->obterParams();
} // Fim if

?>
[DL3-CONTEUDO]
    <div id="album"></div>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
	//<![CDATA[
	$('#album')._galeria({
		minis: true,
		naveg: true,
		indicador: true,
		fotos: [
			<?php foreach( $params['fotos'] as $f ): ?>
			{
				src: '<?php echo \DL3::$dir_relativo . $f['foto_album_imagem']; ?>',
				titulo: '<?php echo $f['foto_album_titulo']; ?>',
				descr: '<?php echo $f['foto_album_descr']; ?>'
			},
			<?php endforeach; ?>
		]
	});
</script>
[/DL3-SCRIPTS]