<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 03/02/2015 12:36:09
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

?>
[DL3-CONTEUDO]
<div id="album"></div>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script src="<?php echo \DL3::$dir_relativo . \DL3::$dir_js; ?>dl-galeria/dl-galeria-3.0.plugin-min.js"></script>

<script>
    //<![CDATA[
    (function ($) {
        $('#album').galeriaFotos({
            minis: true,
            naveg: true,
            indicador: true,
            fotos: <?php echo json_encode($params['fotos']); ?>,
            animacao: 'esquerda-para-direita .35s linear',
            botaofechar: true,
            teclaesc: true,
            tema: '<?php echo $params['config-album']['configuracao_album_tema']; ?>'
        });
    })(jQuery);
</script>
[/DL3-SCRIPTS]