<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

if( !isset($params) ){
	$params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_GRUPO; ?></legend>

            <p class="form-paragr">
                <?php echo $this->aux_form->campoGeral('texto', 'descr', 'descr', $mod->descr, TXT_ROTULO_NOME, null, ['required' => 'required']); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->chkSimNao('publicar', 'chk-publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
            </p>
        </fieldset>

        <?php if( $params['mostrar-perms?'] ): ?>
        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_PERMISSOES; ?></legend>

            <ul class="grp-funcs">
                <?php
                    foreach( $params['menu-modulos'] as $mm ):
                        $sm_k = array_keys(preg_grep(
                            "~^{$mm['modulo_id']}$~",
                            array_column($params['sub-modulos'], 'modulo_pai')
                        ));

                        if( count($sm_k) > 0 ): ?>
                        <li class="grp-modulo">
                            <p class="grp-nm-modulo"><?php echo $mm['modulo_nome']; ?></p>

                            <?php foreach( $sm_k as $k1 ):
	                            $sm = $params['sub-modulos'][$k1];
                                $fc_k = array_keys(preg_grep(
                                    "~^{$sm['modulo_id']}$~",
                                    array_column($params['funcs'], 'func_modulo')
                                ));

                                if( count($fc_k) > 0 ): ?>
                                <p class="grp-nm-submodulo"><?php echo $sm['modulo_nome']; ?></p>

                                <ul class="grp-submodulo flex-grade">
                                    <?php foreach( $fc_k as $k2 ):
                                        $fc = $params['funcs'][$k2]; ?>
                                        <li class="grp-func flex-item seis-col">
                                            <input type="checkbox" name="funcs[]" id="func-mod-<?php echo $fc['func_modulo_id']; ?>" value="<?php echo $fc['func_modulo_id']; ?>"
                                                <?php echo in_array($fc['func_modulo_id'], $mod->funcs) ? ' CHECKED' : ''; ?>/>
                                            <label for="func-mod-<?php echo $fc['func_modulo_id']; ?>"><?php echo $fc['func_modulo_descr']; ?></label>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>

                                <input type="checkbox" id="selc-todos-<?php echo $k1; ?>"<?php echo !$params['incluindo'] ? ' CHECKED' : ''; ?>/>
                                <label for="selc-todos-<?php echo $k1; ?>" class="form-rotulo"><?php echo TXT_ROTULO_SELECIONAR_TODOS; ?></label>
                                <?php endif;
                            endforeach; ?>
                        </li>
                        <?php endif;
                    endforeach;
                ?>
            </ul>
        </fieldset>
        <?php endif;

        if( !$params['incluindo'] ): ?>
        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_MEMBROS; ?></legend>

            <table class="lista-registros">
                <thead class="tbl-titulos">
                    <tr class="tbl-linha">
                        <?php echo $this->aux_lista->celulaTitulo('nome', TXT_LISTA_TITULO_NOME); ?>
                    </tr>
                </thead>

                <tbody class="tbl-conteudo">
                    <?php if( !count($params['membros']) ){
	                    echo '<tr class="tbl-linha sem-registros"><td>', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';
                    } // Fim if( !count($params['membros']) )

                    foreach( $params['membros'] as $l ): ?>
	                    <tr class="tbl-linha">
		                    <?php echo $this->aux_lista->celulaComum('nome', $l['usuario_info_nome']); ?>
	                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </fieldset>
        <?php endif; ?>

        <p class="form-botoes">
            <?php
            echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
            echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
            ?>
        </p>
    </form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    // Selecionar todos os checkbox de um determinado sub-módulo
    (function($){
	    $(':checkbox[id^="selc-todos-"]').on('change', function(){
		    $(this).each(function(){
			    var $th = $(this);
			    var chk = $th.prop('checked');

			    $th.prev().find(':checkbox').each(function(){
				    $(this).prop('checked', chk);
			    });
		    });
	    });

	    $('.grp-submodulo :checkbox').not(':checked').parents('.grp-submodulo').each(function(){
		    $(this).next().prop('checked', false);
	    });
    })(jQuery);
    //]]>
</script>
[/DL3-SCRIPTS]