<?php

/**
 * @Autor	: Diego Lepera
 * @E-mail	: d_lepera@hotmail.com
 * @Projeto	: FrameworkDL
 * @Data	: 07/01/2015 18:34:49
 */

/*
 * CORRIGIR: O recurso 'Testar configuração' deve levar em consideração o que está no formulário e não o que está salvo no banco de dados
 */

if( !isset($params) ){
	$params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
    <form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
        <?php if( !$params['incluindo'] ): ?>
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
        <?php endif; ?>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_SERVIDOR; ?></legend>

            <p class="form-paragr">
	            <?php echo $this->aux_form->campoGeral('texto', 'titulo', 'titulo', $mod->titulo, TXT_ROTULO_TITULO, null, [
	                'required' => 'required'
                ]); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->campoGeral('texto', 'host', 'host', $mod->host, TXT_ROTULO_HOST, null, [
		            'placeholder' => TXT_EXEMPLO_HOST_SMTP, 'required' => 'required'
	            ]); ?> :

	            <?php echo $this->aux_form->campoGeral('numero', 'porta', 'porta', $mod->porta, null, null, [
		            'required' => 'required', 'min' => 1, 'max' => 65535
	            ]); ?>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_AUTENTICACAO; ?></legend>

            <p class="form-paragr">
	            <?php echo $this->aux_form->chkSimNao('autent', 'chk-autent', TXT_ROTULO_REQUER_AUTENT, null, $mod->autent ? 'CHECKED' : ''); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->comboSelect('cripto', 'cripto', $mod->cripto, TXT_ROTULO_TIPO_CRIPTO, null, [], [
		            ['VALOR' => '', 'TEXTO' => TXT_OPCAO_NENHUMA],
		            ['VALOR' => 'tls', 'TEXTO' => TXT_OPCAO_TLS],
		            ['VALOR' => 'ssl', 'TEXTO' => TXT_OPCAO_SSL]
	            ]); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->campoGeral('texto', 'conta', 'conta', $mod->conta, TXT_ROTULO_CONTA); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->campoGeral('senha', 'senha', 'senha', $mod->senha, TXT_ROTULO_SENHA); ?>
            </p>
        </fieldset>

        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_CONFIGURACOES_ENVIO; ?></legend>

            <p class="form-paragr">
	            <?php echo $this->aux_form->campoGeral('texto', 'de_nome', 'de-nome', $mod->de_nome, TXT_ROTULO_DE_NOME, null, [
		            'required' => 'required'
	            ]); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->campoGeral('email', 'de_email', 'de-email', $mod->de_email, TXT_ROTULO_DE_EMAIL, null, [
		            'placeholder' => TXT_EXEMPLO_EMAIL, 'required' => 'required'
	            ]); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->campoGeral('email', 'responder_para', 'responder-para', $mod->responder_para, TXT_ROTULO_RESPONDER_PARA, null, [
		            'placeholder' => TXT_EXEMPLO_EMAIL, 'required' => 'required'
	            ]); ?>
            </p>

            <p class="form-paragr">
	            <?php echo $this->aux_form->chkSimNao('html', 'chk-html', TXT_ROTULO_HTML, TXT_DICA_EMAIL_HTML, $mod->html ? 'CHECKED' : ''); ?>
            </p>
        </fieldset>

        <p class="form-paragr">
	        <?php echo $this->aux_form->chkSimNao('principal', 'chk-principal', TXT_ROTULO_PRINCIPAL, TXT_DICA_EMAIL_PRINCIPAL, $mod->principal ? 'CHECKED' : ''); ?>
        </p>

	    <p class="form-paragr">
		    <?php echo $this->aux_form->chkSimNao('debug', 'chk-debug', TXT_ROTULO_DEBUG, TXT_DICA_DEBUG, $mod->debug ? 'CHECKED' : ''); ?>
	    </p>

        <p class="form-botoes">
            <?php
            echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
            echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);

            if( !$params['incluindo'] && $params['perm-testar?'] ): ?>
                <a href="javascript:"
                   onclick="$sf._executar('admin/envio-de-emails/testar-configuracao/<?php echo $mod->id; ?>');"
                   data-ajax="1" data-ajax-msg="<?php echo TXT_AJAX_ENVIANDO_EMAIL; ?>" class="com-icone ico-email">
                    <?php echo TXT_LINK_TESTAR_CONFIGURACAO; ?>
                </a>
            <?php endif; ?>
        </p>
    </form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    (function($){
        var $requer_autent = $('#chk-autent');
        var $acesso_conta = $('#txt-conta, #sen-senha');

        $requer_autent.on('change.__script', function(){
            $acesso_conta.prop('required', $requer_autent.prop('checked'))
        });
    })(jQuery);
    //]]>
</script>
[/DL3-SCRIPTS]