<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 07/01/2015 18:34:49
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$mod = $params['modelo'];

?>

[DL3-CONTEUDO]
<form id="form-<?php echo $params['form-id']; ?>" method="post" action="<?php echo $params['form-action']; ?>">
    <?php if (!$params['incluindo']): ?>
        <input type="hidden" name="id" value="<?php echo $mod->id; ?>"/>
    <?php endif; ?>

    <fieldset class="form-grupo">
        <legend class="form-legenda"><?php echo TXT_LEGENDA_GRUPO; ?></legend>

        <p class="form-paragr">
            <?php echo $this->aux_form->campoGeral('texto', 'descr', 'descr', $mod->descr, TXT_ROTULO_NOME, null, ['required' => 'required']); ?>
        </p>

        <p class="form-paragr">
            <?php echo $this->aux_form->chkSimNao('publicar', 'chk-publicar', TXT_ROTULO_PUBLICAR, null, $mod->publicar ? ' CHECKED' : ''); ?>
        </p>
    </fieldset>

    <?php if ($params['mostrar-perms?']): ?>
        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_PERMISSOES; ?></legend>

            <ul class="grupos-x-funcs">
                <?php
                foreach ($params['menu-modulos'] as $mm):
                    $sm_k = array_keys(preg_grep(
                        "~^{$mm['modulo_id']}$~",
                        array_column($params['sub-modulos'], 'modulo_pai')
                    ));

                    if (count($sm_k) > 0): ?>
                        <li class="modulo">
                            <p class="nomemod"><?php echo $mm['modulo_nome']; ?></p>

                            <?php foreach ($sm_k as $k1):
                                $sm = $params['sub-modulos'][$k1];
                                $fc_k = array_keys(preg_grep(
                                    "~^{$sm['modulo_id']}$~",
                                    array_column($params['funcs'], 'func_modulo')
                                ));

                                if (count($fc_k) > 0): ?>
                                    <p class="nomesub"><?php echo $sm['modulo_nome']; ?></p>

                                    <ul class="submodulo grade-flexivel">
                                        <?php foreach ($fc_k as $k2):
                                            $fc = $params['funcs'][$k2]; ?>
                                            <li class="func flexitem seis-col">
                                                <input type="checkbox" name="funcs[]"
                                                       id="func-mod-<?php echo $fc['func_modulo_id']; ?>"
                                                       value="<?php echo $fc['func_modulo_id']; ?>"
                                                    <?php echo in_array($fc['func_modulo_id'], $mod->funcs) ? ' CHECKED' : ''; ?>/>
                                                <label
                                                    for="func-mod-<?php echo $fc['func_modulo_id']; ?>"><?php echo $fc['func_modulo_descr']; ?></label>
                                            </li>
                                        <?php endforeach; ?>
                                    </ul>

                                    <label class="selectodos">
                                        <input type="checkbox"<?php echo !$params['incluindo'] ? ' CHECKED' : ''; ?>/>
                                        <?php echo TXT_ROTULO_SELECIONAR_TODOS; ?>
                                    </label>
                                <?php endif;
                            endforeach; ?>
                        </li>
                    <?php endif;
                endforeach;
                ?>
            </ul>
        </fieldset>
    <?php endif;

    if (!$params['incluindo']): ?>
        <fieldset class="form-grupo">
            <legend class="form-legenda"><?php echo TXT_LEGENDA_MEMBROS; ?></legend>

            <table class="lista-registros">
                <thead class="bloco-titulos">
                    <tr class="registro">
                        <?php echo $this->aux_lista->celulaTitulo('nome', TXT_LISTA_TITULO_NOME); ?>
                    </tr>
                </thead>

                <tbody class="bloco-registros">
                <?php if (!count($params['membros'])) {
                    echo '<tr class="registro sem-registros"><td>', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';
                } // Fim if

                foreach ($params['membros'] as $l): ?>
                    <tr class="registro">
                        <?php echo $this->aux_lista->celulaComum('nome', $l['usuario_info_nome']); ?>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </fieldset>
    <?php endif; ?>

    <p class="form-botoes">
        <?php
        echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR);
        echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
        ?>
    </p>
</form>
[/DL3-CONTEUDO]

[DL3-SCRIPTS]
<script>
    //<![CDATA[
    // Selecionar todos os checkbox de um determinado sub-módulo
    (function ($) {
        $('.selectodos > :checkbox').on('change', function () {
            var $th = $(this);
            var chk = $th.prop('checked');

            $th.parent().prev().find(':checkbox').each(function () {
                $(this).prop('checked', chk);
            });
        });

        $('.submodulo :checkbox').not(':checked').parents('.submodulo').each(function () {
            $(this).next().find(':checkbox').prop('checked', false);
        });
    })(jQuery);
    //]]>
</script>
[/DL3-SCRIPTS]