<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 10/01/2015 11:14:18
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

?>

[DL3-CONTEUDO]
<?php if ($params['msg-reset?']): ?>
    <p class="mostrar-msg -info"><?php echo TXT_DIVERSOS_RESET_SENHA_PROX_LOGIN; ?></p>
<?php endif; ?>

<form id="form-<?php echo $params['form-id']; ?>" method="post"
      action="<?php echo preg_replace('~^[a-z0-9A-Z]+/~', 'admin/', $params['form-action']); ?>">
    <p class="form-paragr">
        <?php echo $this->aux_form->campoGeral('senha', 'senha_atual', 'senha-atual', '', TXT_ROTULO_SENHA_ATUAL, null, ['required' => 'required']); ?>
    </p>

    <p class="form-paragr">
        <?php echo $this->aux_form->campoGeral('senha', 'senha_nova', 'senha-nova', '', TXT_ROTULO_SENHA_NOVA, null, ['required' => 'required']); ?>
    </p>

    <p class="form-paragr">
        <?php echo $this->aux_form->campoGeral('senha', 'senha_nova_conf', 'senha-nova-conf', '', TXT_ROTULO_SENHA_NOVA_CONF, null, ['required' => 'required']); ?>
    </p>

    <p class="form-botoes">
        <?php
        echo $this->aux_form->botao('salvar', TXT_BOTAO_SALVAR, [
            'data-acao' => 'confirmar-submit', 'data-acao-param-msg' => TXT_DIVERSOS_CONFIRMAR_ALTERAR_SENHA
        ]);
        echo $this->aux_form->botao('cancelar', TXT_BOTAO_CANCELAR);
        ?>
    </p>
</form>
[/DL3-CONTEUDO]
