<?php

/**
 * @Autor      : Diego Lepera
 * @E-mail     : d_lepera@hotmail.com
 * @Projeto    : FrameworkDL
 * @Data       : 07/01/2015 16:51:21
 */

if (!isset($params)) {
    $params = $this->obterParams();
} // Fim if

$opcoes = $params['opcoes'];
$lista = $params['lista'];
$dir_lista = $params['dir-lista'];

$campos = \Funcoes::removerColuna($lista, [TXT_LISTA_TITULO_ID, 'linha']);

?>

[DL3-CONTEUDO]
<nav class="dl3-links">
    <!-- Inserir um novo registro -->
    <?php if ($opcoes['inserir?']) {
        echo $this->aux_links->linkHTML('inserir', "{$dir_lista}novo", $params['link-inserir']);
    } // Fim if ?>
</nav>

<form id="form-editar-lista" method="post" action="<?php echo $params['form-acao']; ?>">
    <!-- Exibir a lista com os registros selecionados -->
    <table class="lista-registros">
        <?php if ($params['qtde-registros'] > 0): ?>
            <caption
                class="subtitulo"><?php printf(TXT_LISTA_SUBTITULO_MOSTRANDO_X_REGISTROS, count($lista), $params['qtde-registros']); ?></caption>
        <?php endif; ?>

        <thead class="bloco-titulos">
        <tr class="registro">
            <th id="th-chk" class="dado -chk"><input type="checkbox"/></th>
            <?php
            if ($params['exibir-id?']) {
                echo $this->aux_lista->celulaTitulo('th-id', TXT_LISTA_TITULO_ID, ['class' => '-id']);
            } // Fim if

            foreach ($campos[0] as $tt => $lt) {
                echo $this->aux_lista->celulaTitulo($this->aux_lista->thID($tt), $tt);
            } // Fim foreach

            echo $this->aux_lista->celulaTitulo('th-opcoes', TXT_LISTA_TITULO_OPCOES, ['class' => '-opcoes']);
            ?>
        </tr>
        </thead>

        <tbody class="bloco-registros">
        <?php if (!count($lista)) {
            echo '<tr class="registro sem-registros"><td>', MSG_PADRAO_NENHUM_REGISTRO_ENCONTRADO, '</td></tr>';
        } // Fim if

        foreach ($lista as $k => $l): ?>
            <tr class="registro">
                <td headers="th-chk" class="dado -chk">
                    <input type="checkbox" name="id[]" value="<?php echo $l[TXT_LISTA_TITULO_ID]; ?>"/>
                </td>

                <?php if ($params['exibir-id?']) {
                    echo $this->aux_lista->celulaComum('th-id', $l[TXT_LISTA_TITULO_ID], ['class' => '-id'], TXT_LISTA_TITULO_ID);
                } // Fim if

                foreach ($campos[$k] as $k2 => $c) {
                    echo $this->aux_lista->celulaComum($this->aux_lista->thID($k2), $c,
                        ['class' => preg_match('~<br\/?>~', $c) ? '-infos' : null], $k2);
                } // Fim foreach ?>

                <td headers="th-opcoes" class="dado -opcoes" data-th="<?php echo TXT_LISTA_TITULO_OPCOES; ?>">
                    <?php
                    # Editar esse registro
                    if ($opcoes['editar?']) {
                        echo $l[TXT_LISTA_TITULO_BLOQUEADO] === 'Sim'
                            ? $this->aux_links->linkHTML('desbloquear', 'javascript:', TXT_LINK_DESBLOQUEAR, TXT_LINK_TITLE_DESBLOQUEAR_USUARIO, false, [
                                'data-acao-param-dir' => "{$dir_lista}desbloquear-usuarios"
                            ])
                            : $this->aux_links->linkHTML('bloquear', 'javascript:', TXT_LINK_BLOQUEAR, TXT_LINK_TITLE_BLOQUEAR_USUARIO, false, [
                                'data-acao-param-dir' => "{$dir_lista}bloquear-usuarios"
                            ]);

                        echo $this->aux_links->linkHTML('editar', "{$dir_lista}editar/{$l[TXT_LISTA_TITULO_ID]}", TXT_LINK_EDITAR, TXT_LINK_TITLE_EDITAR, false);
                    } // Fim if

                    # Remover esse registro
                    if ($opcoes['remover?']) {
                        echo $this->aux_links->linkHTML('remover', 'javascript:', TXT_LINK_REMOVER, TXT_LINK_TITLE_REMOVER, false);
                    } // Fim if ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>

        <tfoot class="bloco-rodape">
        <?php if (count($lista)): ?>
            <tr class="registro -acoes">
                <td class="dado">
                    <?php
                    if ($opcoes['editar?']) {
                        echo $this->aux_links->linkHTML('desbloquear', 'javascript:', TXT_LINK_DESBLOQUEAR, TXT_LINK_TITLE_DESBLOQUEAR_USUARIO, false, [
                            'data-acao-param-dir' => "{$dir_lista}desbloquear-usuarios"
                        ]);

                        echo $this->aux_links->linkHTML('bloquear', 'javascript:', TXT_LINK_BLOQUEAR, TXT_LINK_TITLE_BLOQUEAR_USUARIO, false, [
                            'data-acao-param-dir' => "{$dir_lista}bloquear-usuarios"
                        ]);
                    } // Fim if

                    # Remover registros
                    if ($opcoes['remover?']) {
                        echo $this->aux_links->linkHTML('remover', 'javascript:', TXT_LINK_REMOVER, TXT_LINK_TITLE_REMOVER_SELECIONADOS, false);
                    } // Fim if ?>
                </td>
            </tr>
        <?php endif; ?>
        </tfoot>
    </table>
</form>

<div id="paginacao"></div>
[/DL3-CONTEUDO]